spring:
  application:
    name: RefineryService
  datasource:
    url: ${database_address}
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8080