services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}