spring:
  application:
    name: ParsingService
  datasource:
    url: ${database_address}
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

file:
  path: ${file_path}